spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fall_blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


#  配置文件接管了后这里就没用了
#  security:
#    user:
#      name: root
#      password: 123456


server:
  port: 8081
#mybatis:
#  configuration:
#    log-prefix: LOG4J

#  1. logging.level.yourdaoclasspackagename=debug
#logging:
#  level:
#    com.flywinter.fallblog.dao: debug
logging:
  level:
    com.flywinter: debug
#  2. mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl